#!/bin/sh /etc/rc.common

START=99

start()
{
	all_pcis=`lspci | grep -i 'eth' | grep -i 'x550' | cut -d ' ' -f 1`
	all_ifs=`cat /proc/net/dev | grep -i 'eth' | cut -d :  -f 1 | sed 's/^[ \t]*//g'`

	for ifname in ${all_ifs}
	do
		if_pci=`ethtool -i ${ifname} | grep -i 'bus-info' | cut -b 16-`
		if [[ "$all_pcis" =~ "$if_pci" ]]
		then
			ethtool -s ${ifname} advertise 0x1800000001028
		fi
	done
}
